### ISSUE TITLE
pretrained model (model_epoch_930.pth)

### ISSUE THREAD

**Issue by ghost** [wangyuxin87/R-Net#1]
@wangyuxin87 upload your pretrained model.
perhaps `model_epoch_930.pth`

**Comment by wangyuxin87** [comment]
> @wangyuxin87 upload your pretrained model.
> perhaps `model_epoch_930.pth`

We have submit our trained model. The pretrained model can be easy obtained by pretraining the model on SynthText for 1 epoch. ( Synthtext:http://www.robots.ox.ac.uk/~vgg/data/scenetext/)
