### ISSUE TITLE
training takes very long time

### ISSUE THREAD

**Issue by ghost** [wangyuxin87/R-Net#5]
@wangyuxin87 the training takes very long time compared  to SakuraRiven EAST.
it not converging well.

**Comment by wangyuxin87** [comment]
> @wangyuxin87 the training takes very long time compared to SakuraRiven EAST.
> it not converging well.

Sorry for the late reply. 
The training is a little long for our model. You can use Synthtext to pretrain the model and easily get similar state-of-the-art result as our published.

**Comment by deepseek** [comment]
@wangyuxin87 how can I use your pretrained model as a base, and further train it on my data?
